config/routes.rb
Rails.application.routes.draw do
  resources :landmarks
  resources :services
  devise_for :users
  resources :hotels do
    resources :commentaries
  end
  root "hotels#index"
end

app/models/landmark.rb
class Landmark < ActiveRecord::Base

  has_many :hotellandmarks
  has_many :hotels, :through => :hotellandmarks

end

app/controllers/landmarks_controller.rb
class LandmarksController < ApplicationController
  before_action :set_landmark, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:show,:new,:edit,:update,:destroy]
  # GET /landmarks
  # GET /landmarks.json
  def index
    @landmarks = Landmark.all
  end

  # GET /landmarks/1
  # GET /landmarks/1.json
  def show
  end

  # GET /landmarks/new
  def new
    @landmark = Landmark.new
  end

  # GET /landmarks/1/edit
  def edit
  end

  # POST /landmarks
  # POST /landmarks.json
  def create
    @landmark = Landmark.new(landmark_params)

    respond_to do |format|
      if @landmark.save
        format.html { redirect_to @landmark, notice: 'Landmark was successfully created.' }
        format.json { render :show, status: :created, location: @landmark }
      else
        format.html { render :new }
        format.json { render json: @landmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /landmarks/1
  # PATCH/PUT /landmarks/1.json
  def update
    respond_to do |format|
      if @landmark.update(landmark_params)
        format.html { redirect_to @landmark, notice: 'Landmark was successfully updated.' }
        format.json { render :show, status: :ok, location: @landmark }
      else
        format.html { render :edit }
        format.json { render json: @landmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /landmarks/1
  # DELETE /landmarks/1.json
  def destroy
    @landmark.destroy
    respond_to do |format|
      format.html { redirect_to landmarks_url, notice: 'Landmark was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_landmark
      @landmark = Landmark.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def landmark_params
      params.require(:landmark).permit(:name)
    end
end

app/helpers/landmarks_helper.rb
module LandmarksHelper
end

app/views/landmarks/_form.html.erb
<%= simple_form_for(@landmark) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/landmarks/edit.html.erb
<h1>Editing Landmark</h1>

<%= render 'form' %>

<%= link_to 'Show', @landmark %> |
<%= link_to 'Back', landmarks_path %>

app/views/landmarks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Landmarks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @landmarks.each do |landmark| %>
      <tr>
        <td><%= landmark.name %></td>
        <td><%= link_to 'Show', landmark %></td>
        <td><%= link_to 'Edit', edit_landmark_path(landmark) %></td>
        <td><%= link_to 'Destroy', landmark, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Landmark', new_landmark_path %>

app/views/landmarks/new.html.erb
<h1>New Landmark</h1>

<%= render 'form' %>

<%= link_to 'Back', landmarks_path %>

app/views/landmarks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @landmark.name %>
</p>

<%= link_to 'Edit', edit_landmark_path(@landmark) %> |
<%= link_to 'Back', landmarks_path %>