config/routes.rb
Rails.application.routes.draw do
  resources :landmarks
  resources :services
  devise_for :users
  resources :hotels do
    resources :commentaries
  end
  root "hotels#index"
end

app/models/commentary.rb
class Commentary < ActiveRecord::Base
  belongs_to :hotel
  belongs_to :user

  validates :comment, :presence => true
  validates :score, :presence => true
end

app/controllers/commentaries_controller.rb
class CommentariesController < ApplicationController
  before_action :find_hotel
  before_action :find_commentary, only: [:edit,:update,:destroy]
  before_action :authenticate_user!, only: [:new,:edit]

  def new
    @commentary = Commentary.new
  end

  def create
    @commentary = Commentary.new(commentary_params)
    @commentary.hotel_id= @hotel.id
    @commentary.user_id = current_user.id


      if @commentary.save
        redirect_to hotel_path(@hotel)
      else
        respond_to do |format|
        format.html { redirect_to new_hotel_commentary_path(@hotel), notice: 'Comment was not successfully created.' }
      end
    end

  end

  def edit
  end

  def update
    if @commentary.update(commentary_params)
      redirect_to hotel_path(@hotel)
    else
      render 'edit'
    end
  end

  def destroy
    @commentary.destroy
    redirect_to hotel_path(@hotel)
  end

  private

  def commentary_params
    params.require(:commentary).permit(:score, :comment)
  end

  def find_hotel
    @hotel = Hotel.find(params[:hotel_id])
  end

  def find_commentary
    @commentary = Commentary.find(params[:id])
  end

end

app/helpers/commentaries_helper.rb
module CommentariesHelper
end

app/views/commentaries/_commentary.html.erb
<tr>

  <td><div class='star-rating' data-score="<%= commentary.score %>"></div></td>
  <td><p data-toggle="tooltip" title="<%= commentary.user.name %>"><%= commentary.comment%></p></td>
  <% if user_signed_in? %>
  <% if commentary.user.id == current_user.id %>
          <td><div class="dropdown">
            <button class="btn btn-warning btn-xs dropdown-toggle" type="button" data-toggle="dropdown"><span class="glyphicon glyphicon-cog" aria-hidden="true">&nbsp;</span><span class="caret"></span></button>

              <ul class="dropdown-menu">
                <li><a href="<%= edit_hotel_commentary_path(commentary.hotel,commentary)%>"><span class="glyphicon glyphicon-pencil" aria-hidden="true">&nbsp;Edit</span></a></li>
                <li><a href="<%=hotel_commentary_path(commentary.hotel,commentary) %>"  data-confirm="Are you sure?" data-method="delete" data-original-title="Delete" rel="nofollow"><span class="glyphicon glyphicon-trash" aria-hidden="true">&nbsp;Delete</span></a></li>
              </ul>
          </div></td>
      <% end %>
  <% end %>
</tr>

app/views/commentaries/_form.html.erb
<%= simple_form_for([@hotel,@hotel.commentaries.build]) do |f| %>
<div id="rating-form">
  <label>Score</label>
</div>

  <%= f.input :comment %>
  <%= f.button :submit %>
<% end %>

<script>
    $('#rating-form').raty({
        path: '/assets/images/ratyrate',
        scoreName: 'commentary[score]'
    });
</script>

app/views/commentaries/edit.html.erb
<h1>Edit commentary</h1>

<%= simple_form_for([@hotel,@commentary]) do |f| %>
    <div id="rating-form">
      <label>Score</label>
    </div>
  <%= f.input :comment %>
  <%= f.button :submit %>
<% end %>

<script>
    $('#rating-form').raty({
        path: '/assets/images/ratyrate',
        scoreName: 'commentary[score]'
    });
</script>

app/views/commentaries/new.html.erb
<h1>New comment</h1>


<%= render 'form' %>