config/routes.rb
Rails.application.routes.draw do
  resources :landmarks
  resources :services
  devise_for :users
  resources :hotels do
    resources :commentaries
  end
  root "hotels#index"
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  belongs_to :user
  belongs_to :destination
  belongs_to :city
  has_many :commentaries

  has_many :hotelservices
  has_many :services, :through => :hotelservices
  has_many :hotellandmarks
  has_many :landmarks, :through => :hotellandmarks

  validates :name, :presence => true
  validates :city_id, :presence => true

  has_attached_file :hotel_img, styles: { :hotel_index => "150x250>", :hotel_show => "250x350" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :hotel_img, content_type: /\Aimage\/.*\z/


end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :find_hotel, only:[:show,:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new,:edit]

  def index
    if params[:destination].blank?
      if params[:city].blank?
        @hotels = Hotel.all.order("created_at DESC")
      else
        @city_id = City.find_by(name: params[:city]).id
        @hotels = Hotel.where(:city_id => @city_id).order("created_at DESC")
      end
    else
       @destination_id = Destination.find_by(name: params[:destination]).id
       @hotels = Hotel.where(:destination_id => @destination_id).order("created_at DESC")
    end
  end

  def show
    if @hotel.commentaries.blank?
      @average_comment = 0
    else
      @average_comment = @hotel.commentaries.average(:score).round(2)
    end
  end

  def new
    @hotel = current_user.hotels.build
    @destinations = Destination.all.map{ |d| [d.name,d.id] }
    @cities = City.all.map{ |c| [c.name,c.id] }


    @all_services = Service.all
    @hotel_service = @hotel.hotelservices.build

    @all_landmarks = Landmark.all
    @hotel_landmark = @hotel.hotellandmarks.build


  end

  def create
    @hotel = current_user.hotels.build(hotel_params)
    @hotel.destination_id=params[:destination_id]
    @hotel.city_id=params[:city_id]

    params[:services][:id].each do |service|
      if !service.empty?
        @hotel.hotelservices.build(:service_id => service)
      end
    end

    params[:landmarks][:id].each do |landmark|
      if !landmark.empty?
        @hotel.hotellandmarks.build(:landmark_id => landmark)
      end
    end


    respond_to do |format|
      if @hotel.save
        format.html { redirect_to @hotel, notice: 'Hotel was successfully created.' }
        format.json { render :show, status: :created, location: @hotel }
      else
        format.html { redirect_to new_hotel_path, notice: 'Hotel was not successfully created.' }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end




  end

  def edit
    @destinations = Destination.all.map{ |d| [d.name,d.id] }
    @cities = City.all.map{ |c| [c.name,c.id] }

  end

  def update
    @hotel.destination_id=params[:destination_id]
    @hotel.city_id=params[:city_id]

    if @hotel.update(hotel_params)
      redirect_to hotel_path(@hotel)
    else
      render 'edit'
    end
  end

  def destroy
  @hotel.destroy
    redirect_to root_path
  end

  private

    def hotel_params
      params.require(:hotel).permit(:name,:adress,:price,:description,:destination_id,:city_id,:hotel_img)
    end

    def find_hotel
      @hotel = Hotel.find(params[:id])
    end

end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/hotels/_form.html.erb
<%= simple_form_for @hotel,:html => {:multipart => true} do |f| %>
    <%= f.input :name, label: "Hotel name:" %>
    <%= select_tag(:destination_id,options_for_select(@destinations), :prompt=> "Select destination")  %>
    <%= select_tag(:city_id,options_for_select(@cities), :prompt=> "Select city")  %>
    <%= f.file_field :hotel_img %>
    <%= f.input :adress %>
    <%= f.input :price %>
    <%= f.input :description %>

    <%= fields_for(@hotel_service) do |as| %>
      <%= as.label "All services" %>
        <%= collection_select(:services,:id,@all_services,:id,:name,{},{:multiple => true}) %>
    <% end %>

    <%= fields_for(@hotel_landmark) do |as| %>
        <%= as.label "All landmarks" %>
        <%= collection_select(:landmarks,:id,@all_landmarks,:id,:name,{},{:multiple => true}) %>
    <% end %>




    <%= f.button :submit %>
<% end %>

app/views/hotels/edit.html.erb
<h1>Edit hotel</h1>
<%= simple_form_for @hotel,:html => {:multipart => true} do |f| %>
<%= f.input :name, label: "Hotel name:" %>
    <%= f.select :destination_id, @destinations %>
    <%= f.select :city_id, @cities %>
    <%= f.file_field :hotel_img %>
<%= f.input :adress %>
<%= f.input :price %>
<%= f.input :description %>
<%= f.button :submit %>
<% end %>

app/views/hotels/index.html.erb
<h1 class="current-destination"><%= params[:destination] %></h1>
  <h1 class="current-destination"><%= params[:city] %></h1>
<% if @hotels.count == 0 %>
      <h1>There are no hotels currently in this destination</h1>
<% else %>
    <div class="row">
        <% @hotels.each do |hotel| %>
            <div class="col-md-3">
              <a href="/hotels/<%= hotel.id %>"><%= image_tag hotel.hotel_img.url(:hotel_index), class: "hotel" %></a>
              <br>
              <h3><%= link_to hotel.name,hotel_path(hotel) %></h3>
            </div>
        <% end %>
    </div>

<% end %>

app/views/hotels/new.html.erb
<h1>New hotel</h1>


<%= render 'form' %>

app/views/hotels/show.html.erb
<%= javascript_include_tag 'ratyrate.js', "data-turbolinks-track" => false %>
<div>

<a href=" <%= root_path %>" class="btn btn-danger btn-sm" role="button">Back</a>

</div>

<br>



<div class="row">
  <div class="col-sm-4" style="background-color:white;">
    <%= image_tag @hotel.hotel_img(:hotel_show),class:"hotel-show" %>
    <br>
    <% if user_signed_in? %>
        <% if @hotel.user_id == current_user.id %>
            <div class="dropdown">
              <button class="btn btn-warning btn-sm dropdown-toggle" type="button" data-toggle="dropdown"><span class="glyphicon glyphicon-cog" aria-hidden="true">&nbsp;</span><span class="caret"></span></button>
              <ul class="dropdown-menu">
                <li><a href="<%= edit_hotel_path(@hotel)%>"><span class="glyphicon glyphicon-pencil" aria-hidden="true">&nbsp;Edit</span></a></li>
                <li><a href="<%=hotel_path(@hotel) %>"  data-confirm="Are you sure?" data-method="delete" data-original-title="Delete" rel="nofollow"><span class="glyphicon glyphicon-trash" aria-hidden="true">&nbsp;Delete</span></a></li>
              </ul>
            </div>
        <% end %>
    <% end %>
  </div>


  <div class="col-sm-8" style="background-color:#f0f0f5;">
      <h2>Hotel <%= @hotel.name %>, <%= @hotel.city.name %>, <%= @hotel.destination.name %></h2>
      <p><%= @hotel.adress %></p>

    <h3>Average score</h3>
    <div class="average-review-rating" data-score=<%= @average_comment %>></div>
    <span>Calculated based on <%= @hotel.commentaries.count %> ratings.</span>

    <h4>Price: <span class="label label-success"><%= @hotel.price %> EUR/Night</span></h4>


    <div class="col-lg-6" style="background-color:#f0f0f5;">
      <h3>Services</h3>
      <% Hotelservice.all.each do |hservice| %>
          <% if hservice.hotel_id ==@hotel.id %>
              <p><%= Service.find(hservice.service_id).name %></p>
          <% end %>
      <% end %>
    </div>

    <div class="col-lg-6" style="background-color:#f0f0f5;">
      <h3>Landmarks</h3>
      <% Hotellandmark.all.each do |hlandmark| %>
          <% if hlandmark.hotel_id == @hotel.id %>
              <p><%= Landmark.find(hlandmark.landmark_id).name %></p>
          <% end %>
      <% end %>
    </div>


  </div>
</div>

<div class="row">
  <h2>Description:</h2>
  <p><%= @hotel.description %> </p>
</div>

<div class="row">
    <h3>General commentary</h3>
    <a href="<%= new_hotel_commentary_path(@hotel)%>" class="btn btn-info btn-sm" role="button">Add comment</a>
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Score</th>
        <th>Comment</th>
        <th></th>
      </tr>
      </thead>
      <tbody>

      <%= render @hotel.commentaries %>

      </tbody>
    </table>
</div>






<script>
    $('.star-rating').raty({
        path: '/assets/images/ratyrate',
        readOnly: true,
        score: function() {
            return $(this).attr('data-score');
        }
    });
</script>

<script>
  $('.average-review-rating').raty({
      readOnly: true,
      path: '/assets/images/ratyrate',
      score: function() {
      return $(this).attr('data-score')
  }
  });
</script>

<script>
    $(document).ready(function(){
        $('[data-toggle="tooltip"]').tooltip();
    });
</script>